from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from models import db, User, Order, Swap
from routes.auth import login_required
import secrets
import hashlib
import requests
from datetime import datetime

main_bp = Blueprint('main', __name__)

@main_bp.route('/tutorial')
def tutorial():
    return render_template('tutorial.html')

@main_bp.route('/')
def index():
    if 'user_id' in session:
        return redirect(url_for('main.dashboard'))
    return render_template('index.html')

@main_bp.route('/dashboard')
@login_required
def dashboard():
    user = User.query.get(session['user_id'])
    my_orders = Order.query.filter_by(user_id=user.id).all()
    # Filter swaps where user is either the order creator or the matcher
    my_swaps = Swap.query.join(Order).filter(
        (Order.user_id == user.id) | (Swap.matcher_id == user.id)
    ).all()
    return render_template('dashboard.html', user=user, orders=my_orders, swaps=my_swaps)

@main_bp.route('/orders', methods=['GET', 'POST'])
@login_required
def orders():
    if request.method == 'POST':
        side = request.form.get('side')
        amount_hns = request.form.get('amount_hns')
        price = request.form.get('price')
        gems_stake = request.form.get('gems_stake') or 0
        
        try:
            order = Order(
                user_id=session['user_id'],
                side=side,
                amount_hns=float(amount_hns),
                price_btc_per_hns=float(price),
                gems_stake=int(gems_stake)
            )
            db.session.add(order)
            db.session.commit()
            flash('Order created successfully!', 'success')
            return redirect(url_for('main.orders'))
        except Exception as e:
            flash(f'Error creating order: {str(e)}', 'error')

    orders = Order.query.filter_by(status='open').order_by(Order.created_at.desc()).all()
    
    # Get current HNS price in BTC
    try:
        response = requests.get('https://api.coingecko.com/api/v3/simple/price?ids=handshake&vs_currencies=btc')
        if response.status_code == 200:
            current_price = response.json().get('handshake', {}).get('btc', 0.00000050)
        else:
            current_price = 0.00000050
    except Exception as e:
        print(f"CoinGecko API Error: {e}")
        current_price = 0.00000050
        
    return render_template('orders.html', orders=orders, current_price=current_price)

@main_bp.route('/orders/<int:order_id>/accept', methods=['POST'])
@login_required
def accept_order(order_id):
    order = Order.query.get_or_404(order_id)
    matcher_id = session['user_id']
    
    if order.user_id == matcher_id:
        flash('You cannot accept your own order.', 'error')
        return redirect(url_for('main.orders'))
        
    if order.status != 'open':
        flash('Order is no longer available.', 'error')
        return redirect(url_for('main.orders'))

    # Generate secret and hash
    secret = secrets.token_hex(32)
    secret_hash = hashlib.sha256(bytes.fromhex(secret)).hexdigest()
    
    # Determine roles
    # If order is SELL HNS: User is Alice (locks HNS first). Matcher is Bob.
    # If order is BUY HNS: User is Bob. Matcher is Alice (locks HNS first).
    if order.side == 'sell':
        role_alice_id = order.user_id
    else:
        role_alice_id = matcher_id
        
    swap = Swap(
        order_id=order.id,
        matcher_id=matcher_id,
        secret_hash=secret_hash,
        role_alice_user_id=role_alice_id,
        status='initiated'
    )
    
    order.status = 'matched'
    db.session.add(swap)
    db.session.commit()
    
    # In a real app, we would securely share the secret with the appropriate party
    # For this MVP, we might display it to the generator (matcher) once?
    # Actually, the secret should be generated by the party who needs to reveal it later.
    # Usually, the initiator (Alice) generates the secret.
    # Here, we simplify: The platform generates it and shows it to both? No, that defeats the purpose.
    # Let's stick to the plan: "generate secret + hash".
    # We'll show the secret to the Matcher (who is initiating the swap logic in this flow?)
    # Wait, HTLC logic:
    # 1. Alice generates secret S, hash H(S).
    # 2. Alice locks funds with H(S) & Timelock T1.
    # 3. Bob sees lock, locks funds with H(S) & Timelock T2 (T2 < T1).
    # 4. Alice reveals S to claim Bob's funds.
    # 5. Bob sees S, claims Alice's funds.
    
    # In our flow:
    # If Order is SELL HNS (Maker has HNS, wants BTC):
    #   Maker = Alice (has HNS). Taker = Bob (has BTC).
    #   Taker accepts order.
    #   Ideally, Taker (Bob) should wait for Maker (Alice) to lock HNS.
    #   Alice needs S.
    #   So Alice should generate S.
    #   But here Taker is clicking "Accept".
    #   If Taker clicks accept, we can't easily make Alice generate S immediately (she's offline).
    #   
    #   Alternative:
    #   Taker generates S. Taker = Alice?
    #   If Order is SELL HNS (Maker=Alice, Taker=Bob).
    #   If Taker generates S, Taker is Alice? No, Taker has BTC.
    #   
    #   If Taker (Bob) generates S:
    #   Bob locks BTC with H(S).
    #   Alice sees lock, locks HNS with H(S).
    #   Bob reveals S to claim HNS.
    #   Alice sees S, claims BTC.
    #   
    #   This works! "Bob" (BTC holder) can be the initiator of the secret.
    #   
    #   Let's check the other case:
    #   Order is BUY HNS (Maker has BTC, wants HNS).
    #   Maker = Bob. Taker = Alice (has HNS).
    #   Taker (Alice) accepts order.
    #   Taker generates S.
    #   Taker (Alice) locks HNS with H(S).
    #   Maker (Bob) sees lock, locks BTC with H(S).
    #   Taker (Alice) reveals S to claim BTC.
    #   Maker (Bob) sees S, claims HNS.
    #   
    #   So: The Taker (Matcher) can always generate the Secret?
    #   Case 1: Sell HNS. Taker=Bob. Bob generates S. Bob locks BTC first?
    #     Standard is Alice (HNS) locks first.
    #     If Bob locks BTC first, he is effectively Alice in the protocol sense (initiator).
    #     But traditionally Alice is the one with the asset that has the longer timelock?
    #     Actually, the one who locks *first* should have the *longer* timelock (T1).
    #     The one who locks *second* has shorter timelock (T2).
    #     
    #     So if Bob (BTC) locks first (T1), then Alice (HNS) locks second (T2).
    #     Bob reveals S to claim HNS.
    #     Alice uses S to claim BTC.
    #     
    #     This seems fine.
    #     
    #     So, the Matcher (Taker) always generates the Secret.
    #     We store the Secret in the session of the Matcher so they can see it.
    #     We store the Hash in the DB.
    
    session['generated_secret'] = secret
    flash('Swap initiated! You are the initiator. Save your secret!', 'success')
    return redirect(url_for('main.swap_details', id=swap.id))

@main_bp.route('/orders/<int:order_id>/cancel', methods=['POST'])
@login_required
def cancel_order(order_id):
    order = Order.query.get_or_404(order_id)
    
    if order.user_id != session['user_id']:
        flash('You can only cancel your own orders.', 'error')
        return redirect(url_for('main.dashboard'))
        
    if order.status != 'open':
        flash('Cannot cancel order. It may have already been matched or canceled.', 'error')
        return redirect(url_for('main.dashboard'))
        
    order.status = 'canceled'
    db.session.commit()
    
    flash('Order canceled successfully.', 'success')
    return redirect(url_for('main.dashboard'))

@main_bp.route('/swaps/<int:id>')
@login_required
def swap_details(id):
    swap = Swap.query.get_or_404(id)
    user = User.query.get(session['user_id'])
    
    # Check if user is involved
    if user.id != swap.order.user_id and user.id != swap.matcher_id:
        flash('You do not have permission to view this swap.', 'error')
        return redirect(url_for('main.dashboard'))
        
    secret = session.get('generated_secret') if swap.matcher_id == user.id else None
    
    # Get coingecko price (mock for now or real request)
    try:
        # response = requests.get('https://api.coingecko.com/api/v3/simple/price?ids=handshake&vs_currencies=btc')
        # price = response.json()['handshake']['btc']
        price = 0.00000050 # Placeholder
    except:
        price = 0.00000000
        
    return render_template('swap.html', swap=swap, user=user, secret=secret, coingecko_price=price)
